services:
  - type: worker
    name: astre-market-bot
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATA_FILE
        value: /data/data.json
      - key: DISCORD_TOKEN
        sync: false
      - key: TICKET_CATEGORY_ID
        sync: false
      - key: STAFF_ROLE_ID
        sync: false
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
